version: 2.1
orbs:
  node: circleci/node@4.1
  heroku: circleci/heroku@1.0.1
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
workflows:
  build-deploy:
    jobs:
      - build
      - heroku/deploy-via-git:
          requires:
            - build
          filters:
            branches:
              only:
                - main
